"""empty message

Revision ID: 0181c2044a94
Revises: 388ce99c77ca
Create Date: 2025-02-27 10:32:07.969845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0181c2044a94"
down_revision: str | None = "388ce99c77ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("type", sa.Enum("TYPE1", "TYPE2", name="projecttype"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, comment="Date of created"),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="Date of last updated"),
        sa.CheckConstraint("length(name) >= 1", name="name_min_length"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_id"), "project", ["id"], unique=False)
    op.create_index(op.f("ix_project_user_id"), "project", ["user_id"], unique=False)
    op.drop_index("ix_feedback_user_id", table_name="feedback")
    op.drop_constraint("feedback_user_id_fkey", "feedback", type_="foreignkey")
    op.drop_column("feedback", "user_id")
    op.add_column("user", sa.Column("password_hash", sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_hash")
    op.add_column("feedback", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        "feedback_user_id_fkey", "feedback", "user", ["user_id"], ["id"], onupdate="CASCADE", ondelete="CASCADE"
    )
    op.create_index("ix_feedback_user_id", "feedback", ["user_id"], unique=False)
    op.drop_index(op.f("ix_project_user_id"), table_name="project")
    op.drop_index(op.f("ix_project_id"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
