"""empty message

Revision ID: 388ce99c77ca
Revises: d1660df2cf44
Create Date: 2025-02-25 13:47:19.543498

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "388ce99c77ca"
down_revision: str | None = "d1660df2cf44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.VARCHAR(length=254), nullable=False))
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
