"""empty message

Revision ID: d1660df2cf44
Revises:
Create Date: 2025-02-20 17:35:01.893594

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d1660df2cf44"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, comment="Date of created"),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="Date of last updated"),
        sa.Column("is_deleted", sa.BOOLEAN(), server_default="false", nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="Date of deletion"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.VARCHAR(length=254), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=500), nullable=False),
        sa.Column("is_processed", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, comment="Date of created"),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="Date of last updated"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_user_id"), "feedback", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_user_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_table("user")
    # ### end Alembic commands ###
